### ISSUE TITLE
The process remains after closing browser since version 92

### ISSUE THREAD

**Issue by x5ERZzk** [ungoogled-software/ungoogled-chromium-windows#101] opened 2021-10-04 02:49 UTC
Hello,
Since version 92 of Ungoogled Chromium the browser process sometimes doesn't exit for a few minutes after closing the browser's window. As a consequence I cannot start the browser again after closing it. It usually happens once in few launches. This has been tested on a clean profile(s), on Windows 10 20H2 and 21H1, on physical hardware and on a virtual machine. I am using binaries from https://github.com/macchrome/macstable/releases (so I really apologize if I shouldn't report this issue here; however builds prior to version 92 close fine).
The regular chromium builds (I have tested a few - versions 93 and 94) from https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/ work fine (even with the same reused profile).
I have not noticed the same issue on Arch Linux (using binaries from chaotic-aur repository).
Does anyone have a similar problem? Does anyone have such problem with their own builds?
Thanks!

Steps to reproduce:
1. Start the browser (can be on a clean profile, it doesn't matter)
2. Close the browser.

All 'chrome.exe' processes should be terminated within a second or so, but remain for a few (around 3) minutes.

**Comment by Nifury** [comment] 2021-10-04 03:35
> Does anyone have a similar problem? Does anyone have such problem with their own builds?

Yes and yes. It seems the browser would hang at `WaitForSingleObject` for a few minutes, but I couldn't locate the root problem.

**Comment by tomasz1986** [comment] 2022-04-18 11:59
I've also encountered this problem plenty of times. Normally, when I close the browser using the "X" button, it does seem to exit correctly most of the time. However, if the browser has been launched by clicking a URL (e.g. in Thunderbird), then it will always hang when trying to close it.

**Comment by UngoogledUsers** [comment] 2022-04-25 22:39
The task persist and appears again when killing it in task manager. does anyone else have this?

**Comment by teeminus** [comment] 2022-06-07 08:16
I managed to reproduce the problem by opening and immediately closing the browser (latest release). I tried two machines but could only reproduce it on one of them...

**Comment by Nifury** [comment] 2022-07-10 05:23
I was able to narrow down the problem but still don't have a clean solution yet. 

https://github.com/chromium/chromium/blob/16f8dbf1595443282c716d2db20f8104afbb5c71/content/browser/storage_partition_impl.cc#L2377-L2380
```C++
  if (pending_tasks_.empty()) {
    std::move(callback_).Run();
    delete this;
  }
```
Two of the tasks task a long time to finish, impeding the closing process. Here are the two tasks (removing these two tasks solve the issue but with unknown side effects):
https://github.com/chromium/chromium/blob/16f8dbf1595443282c716d2db20f8104afbb5c71/content/browser/storage_partition_impl.cc#L2521-L2541

What's common in these two tasks is that they all use `AsyncCall` which posts tasks to [g_storage_task_runner](https://github.com/chromium/chromium/blob/16f8dbf1595443282c716d2db20f8104afbb5c71/content/browser/attribution_reporting/attribution_manager_impl.cc#L75). My best guess is that the corresponding worker thread is not woken up properly, so the tasks in the queue are executed only during the next periodic check.

**Comment by teeminus** [comment] 2022-07-10 08:04
Maybe @Ahrotahn has an idea.

Or can we somehow discuss the problem with the chromium folks?

**Comment by Ahrotahn** [comment] 2022-07-10 12:22
It looks like this is related to the [Attribution Reporting API](https://developer.chrome.com/docs/privacy-sandbox/attribution-reporting/) which happened to have started [migration](https://developer.chrome.com/docs/privacy-sandbox/attribution-reporting-migration/) from it's predecessor in version 92.  

This is something that *should* be handled by the privacy sandbox (which we disable), but it has individual feature flags outside of those options.  

See if disabling both [ConversionMeasurement](https://source.chromium.org/chromium/chromium/src/+/refs/tags/103.0.5060.114:third_party/blink/common/features.cc;l=52) and [PrivacySandboxAggregationService](https://source.chromium.org/chromium/chromium/src/+/refs/tags/103.0.5060.114:content/browser/aggregation_service/aggregation_service_features.cc;l=11) resolves the issue.  You should be able to launch with `--disable-features=ConversionMeasurement,PrivacySandboxAggregationService` to test.  

I'll have to add an update to the privacy sandbox patch to disable those next time I get the chance.

**Comment by Nifury** [comment] 2022-07-10 13:42
@Ahrotahn Yes, works like a charm!

**Comment by PF4Public** [comment] 2022-07-10 15:48
Is this code Windows-only? I don't remember having anything similar on Linux.

**Comment by Ahrotahn** [comment] 2022-07-11 13:03
It's not windows-specific, and I also had no issues with this on linux.  I can only speculate that there is some platform-specific code elsewhere that comes into play or maybe differences in how the compiler handles things on windows.

**Comment by x5ERZzk** [comment] 2024-02-29 16:12
I apologize for late reply. For me the issue is gone. Thank you wholeheartedly @Ahrotahn

**Comment by x5ERZzk** [comment] 2024-02-29 16:12
I apologize for late reply. For me the issue is gone. Thank you wholeheartedly @Ahrotahn

**Closed** 2024-02-29 16:12 UTC
