### ISSUE TITLE
No  password saving offered since v116 windows binaries

### ISSUE THREAD

**Issue by WernerHermann68** [ungoogled-software/ungoogled-chromium-windows#266] opened 2023-09-09 10:02 UTC
'ages' ago it has been a problem to but for a long time it worked fine that a user was asked if he wants to save a new password.
well until version 115,x. ( i am not sure but had been fixed somewhere ind den 90th versions )
with version  116+117 it does not work anymore .. 'automatically'.
( even with a fresh profile an no plugins )

the only way is to import pw or to add them manually in the pw manager.

can someone help ...please ?

**Comment by PF4Public** [comment] 2023-09-09 18:53
Did you use crlauncher or anything like that to install ungoogled-chromium?

**Comment by WernerHermann68** [comment] 2023-09-09 19:38
Hello  ! thanks for reply.

it happens on several systems and yes ... often i use crlauncher.
another way  of installation i use is the installer from https://chromium.woolyss.com/
installing system wide with no auto-update ..like
116.0.5845.180_ungoogled_mini_installer --install --silent --system-level

Right now i tried it another time with the most pure setup.

this system is 
++ windows 10 22H2 3332  x64  german version.

++ i have delete appdata\local\chromium  to be sure nothing old is interfering  ( sorry for my bad english )

++  i have downloaded https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/116.0.5845.180-1.1/ungoogled-chromium_116.0.5845.180-1.1_windows_x64.zip

++ with  the first start ( chrome.exe ...no crlaucher this time or 'near'   new directory to unpack, appdata-profile deleted ) 
    i switched to english ui/language and acitvate 'Offer to save passwords'
     ( i changed language to be sure this is not causing the problem )

++ then i visited 2 sites  with passwords i know ( bkmks.com and gmx.net ... german version of mail.com )
      and no offer to safe pw neither they have been saved.   'Offer to save passwords' still activated.

++ next i downloaded https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/115.0.5790.171-1.1/ungoogled-chromium_115.0.5790.171-1.1_windows_x64.zip  .. unpacked in a different directory but
keeping the fresh profile from above ( no error messages using the newer 16-profile )

++ going again to the same test site bkmks.com  and dang ...  i got the usual offer to save password and it is really saved
      in pw manager. 

and liked i said ... it has been a problem a 'long time ago'  for the windows version 
... its has been fixed somewhere in the  90th version ... if i remember right. ( but maybe it was a different reason  then )

so right now i did everything i could do to find the cause - right ?

again ...thanks for reply. i hope someone  ( you :D ?) can fix it. i am not a programmer and i love the ungoogled version.

**Comment by PF4Public** [comment] 2023-09-09 19:45
@Nifury @teeminus Does it work for you?

**Comment by Nifury** [comment] 2023-09-09 21:12
No, I can confirm that the latest version doesn't offer to save passwords even when this option is turned on.

**Comment by PF4Public** [comment] 2023-09-10 14:17
@Ahrotahn Could it be that we've inadvertently broken password manager for Windows? I cannot reproduce this issue on Linux.

**Comment by WernerHermann68** [comment] 2023-09-10 14:30
When it has been a problem in the past ( until somewhere in the 90th version ? ) it has been a windows-only problem too.
and yes ... i am aware it could be a different cause this time.

sorry  i cant remember the exact version when it has been fixed in the past.

**Comment by teeminus** [comment] 2023-09-10 17:34
I tried [bkmks.com](bkmks.com) with the ungoogled-chromium draft 117.0.5938.48 and did not get a password save dialog, so it seems the problem is still present in the upcomming release.

**Comment by Rusenche** [comment] 2023-09-10 20:59
I confirm this issue.

I acted on this scenario: https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/266#issuecomment-1712586085 on 5-6 sites and nowhere did the browser ask me to save the password.

It turns out that @macchrome versions also have this problem.

As recently as two days ago, it struck me that Ungoogled chromium didn't ask me to save the password when I registered on a site. And I added it manually from here: chrome://settings/passwords.

After tests, I verified that the window notifying if we want to save the password does not work in:
- 116.0.5845.97;
- 116.0.5845.82;
- 116.0.5845.141;
- 117.0.5938.55 (@macchrome).

I tested these versions on @macchrome and the same versions on @teeminus.

The last version with a working popup asking whether to save the password is: 115.0.5790.131 (at @macchrome) and version 115.0.5790.171 (at @teeminus).

**Comment by WernerHermann68** [comment] 2023-09-10 21:17
i can confirm it too   for 117.0.5938.55 (@macchrome).

are 
https://github.com/macchrome/winchrome
and 
https://github.com/ungoogled-software/ungoogled-chromium-windows

connected somehow or totally separated ?  
would it make sense to report it over there too ?

I dont want to annoy someone  :D

**Comment by tomasz1986** [comment] 2023-09-10 21:19
Just for the record, the save password prompt does pop up in the regular Chromium, so this does sound like an Ungoogled Chromium issue.

**Comment by WernerHermann68** [comment] 2023-09-10 21:22
"Just for the record, the save password prompt does pop up in the regular Chromium, so this does sound like an Ungoogled Chromium issue."
right. ( but i try to avoid to switch to the googled-version )

**Comment by PF4Public** [comment] 2023-09-11 01:05
> are https://github.com/macchrome/winchrome and https://github.com/ungoogled-software/ungoogled-chromium-windows
> 
> connected somehow or totally separated ? 

Not entirely. macchrome uses ungoogled-chromium patches (and some other to his liking), but never provided sources of his build system (neither to satisfy GPL terms of Bromite, nor to verify the reproducibility of distributed binaries). For these reasons we do not provide support for binaries obtained outside of [ungoogled-software](https://github.com/ungoogled-software) GitHub organisation and I would not recommend downloading and executing them. Usage of `chrlauncher` is also discouraged with the same reasoning.

> would it make sense to report it over there too ?

No, not really since the issue is most likely in ungoogled-chromium.

**Comment by WernerHermann68** [comment] 2023-09-11 01:18
i see - thanks for explanation.

in the past with this project, but switched  to https://chromium.woolyss.com/ cause i was a little 
'easier' and more comfortable to see the different versions.

now i know better. thanks :D

**Comment by Rusenche** [comment] 2023-09-11 12:47
> @tomasz1986: Just for the record, the save password prompt does pop up in the regular Chromium, so this does sound like an Ungoogled Chromium issue.

I've just tested cromite v._116.0.5845.180-ee26fd10e5e225fd98d6feb98ab76e1fbe72a5b6_ (the latest up-to-date version by @uazo) just for an experiment - it doesn't have the problem mentioned in this thread.

**Comment by uazo** [comment] 2023-09-11 13:09
@PF4Public sorry I cannot help you, I am not familiar with ungoogled patches.
If you have any ideas, I am happy to help, perhaps by checking the code.

**Comment by WernerHermann68** [comment] 2023-09-12 22:59
> @PF4Public sorry I cannot help you, I am not familiar with ungoogled patches. If you have any ideas, I am happy to help, perhaps by checking the code.

confirmed too.
https://github.com/uazo/cromite/releases/download/v116.0.5845.180-ee26fd10e5e225fd98d6feb98ab76e1fbe72a5b6/chrome-win.zip   (v116.0.5845.180) 
*IS* asking to save pw.

btw ... right now i use this one as starter
https://github.com/portapps/ungoogled-chromium-portable
... cause its easier to have seperated chromium projects with seperated profiles.

**Comment by PF4Public** [comment] 2023-09-13 13:18
Should be fixed in https://github.com/ungoogled-software/ungoogled-chromium/pull/2490

**Comment by Rusenche** [comment] 2023-09-13 13:47
I just tested Ungoogled Chromium v.117.0.5938.63-1-r1181205 (latest and current version as of 6 minutes ago) from here https://github.com/macchrome/winchrome/releases/tag/v117.5938.63-M117.0.5938.63-r1181205-Win64 and the problem is solved.

**Comment by WernerHermann68** [comment] 2023-09-13 14:57
confirmed ...  amazing !  :D

who ever fixed  it ... thanks a lot ! 

looking forward for your next release so i can stop using this other version.

**Closed** 2023-09-13 15:41 UTC
