### ISSUE TITLE
patch can't find file

### ISSUE THREAD

**Issue by herozzm** [ungoogled-software/ungoogled-chromium-windows#4] opened 2019-05-07 06:49 UTC
```
INFO: * Applying mojo.patch (6/32)
DEBUG: E:\ungoogled-chromium-windows\build\src\third_party\git\usr\bin\patch.exe -p1 --ignore-whitespace -i E:\ungoogled-chromium-windows\patches\debian_buster\fixes\mojo.patch -d E:\ungoogled-chromium-windows\build\src --no-backup-if-mismatch --forward
(Stripping trailing CRs from patch; use --binary to disable.)
patching file content/shell/BUILD.gn
Hunk #1 succeeded at 144 (offset -1 lines).
Hunk #2 succeeded at 287 (offset 4 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 26
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/chromecast/common/mojom/typemaps.gni
|+++ b/chromecast/common/mojom/typemaps.gni
--------------------------
File to patch:
```

**Comment by herozzm** [comment] 2019-05-09 00:27
I need to download directly for x64 74 version

**Comment by Eloston** [comment] 2019-05-09 20:04
Duplicate of #2.

**Closed by Eloston** 2019-05-09 20:04 UTC
