### ISSUE TITLE
Discord browser app calls issue

### ISSUE THREAD

**Issue by cadenakis** [ungoogled-software/ungoogled-chromium-windows#315] opened 2024-01-26 08:42 UTC
As the title states while using web Discord on ungoogled chrome windows (same issue on debian linux) voice calls don't work. Simply joining any call or voice channel will endlessly show RTC Connecting. No sound in - no sound out.

**Comment by Nifury** [comment] 2024-01-26 17:11
Looks like a duplicate of https://github.com/ungoogled-software/ungoogled-chromium/issues/2516#issuecomment-1729736360

**Comment by PF4Public** [comment] 2024-02-27 14:06
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.

**Closed by PF4Public** 2024-02-27 14:06 UTC
