### ISSUE TITLE
"Clear cookies and site data when you close all windows"

### ISSUE THREAD

**Issue by rasdmr** [ungoogled-software/ungoogled-chromium-windows#283] opened 2023-11-09 12:17 UTC
In the latest release, the "Clear cookies and site data when you close all windows" setting disappeared and now it is impossible to save anything. All history, cache and cookies are deleted by default whenever you exit the browser.

**Comment by tomasz1986** [comment] 2023-11-09 12:30
Duplicate of https://github.com/ungoogled-software/ungoogled-chromium/issues/2590.

**Closed** 2023-11-09 13:08 UTC
